FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
RUN jenkins-plugin-cli --plugins "ssh-slaves slack \
greenballs workflow-aggregator metrics docker-plugin docker-workflow ansible"
                                  
#Groovy post-init script
COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/init.groovy


